/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsocketRouteImport } from './routes/websocket'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordsIndexRouteImport } from './routes/records/index'
import { Route as RecordsCollectionRouteImport } from './routes/records/$collection'
import { Route as AuthSuccessRouteImport } from './routes/auth/success'
import { Route as AuthErrorRouteImport } from './routes/auth/error'

const WebsocketRoute = WebsocketRouteImport.update({
  id: '/websocket',
  path: '/websocket',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIndexRoute = RecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsCollectionRoute = RecordsCollectionRouteImport.update({
  id: '/records/$collection',
  path: '/records/$collection',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/websocket': typeof WebsocketRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/success': typeof AuthSuccessRoute
  '/records/$collection': typeof RecordsCollectionRoute
  '/records': typeof RecordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/websocket': typeof WebsocketRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/success': typeof AuthSuccessRoute
  '/records/$collection': typeof RecordsCollectionRoute
  '/records': typeof RecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/websocket': typeof WebsocketRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/success': typeof AuthSuccessRoute
  '/records/$collection': typeof RecordsCollectionRoute
  '/records/': typeof RecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/metrics'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/users'
    | '/websocket'
    | '/auth/error'
    | '/auth/success'
    | '/records/$collection'
    | '/records'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/metrics'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/users'
    | '/websocket'
    | '/auth/error'
    | '/auth/success'
    | '/records/$collection'
    | '/records'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/metrics'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/users'
    | '/websocket'
    | '/auth/error'
    | '/auth/success'
    | '/records/$collection'
    | '/records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MetricsRoute: typeof MetricsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  WebsocketRoute: typeof WebsocketRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  RecordsCollectionRoute: typeof RecordsCollectionRoute
  RecordsIndexRoute: typeof RecordsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/websocket': {
      id: '/websocket'
      path: '/websocket'
      fullPath: '/websocket'
      preLoaderRoute: typeof WebsocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/': {
      id: '/records/'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$collection': {
      id: '/records/$collection'
      path: '/records/$collection'
      fullPath: '/records/$collection'
      preLoaderRoute: typeof RecordsCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MetricsRoute: MetricsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  WebsocketRoute: WebsocketRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  RecordsCollectionRoute: RecordsCollectionRoute,
  RecordsIndexRoute: RecordsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
